1.Upsampling

2.Downsampling

In [ ]:
import numpy as np
import pandas as pd

#set the random seed for reproducibilty
'''you get the same random numbers every time you run the code.
Think of it as saying:
"Use the same starting point for random number generation."'''


np.random.seed(123)

#create a dataframe with the two classes
n_samples=1000
class_0_ratio=0.9
n_class_0=int(n_samples*class_0_ratio)
n_class_1=n_samples-n_class_0

In [2]:
n_class_0,n_class_1

(900, 100)

In [ ]:
# CREATE MY DATAFRAME WITH IMBALANCED DATASET
'''loc=0 → mean = 0
scale=1 → standard deviation = 1
size=n_class_0 → generate n_class_0 numbers'''

class_0 = pd.DataFrame({
    'feature_1': np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature_2': np.random.normal(loc=0, scale=1, size=n_class_0),
    'target': [0] * n_class_0
})

class_1 = pd.DataFrame({
    'feature_1': np.random.normal(loc=2, scale=1, size=n_class_1),
    'feature_2': np.random.normal(loc=2, scale=1, size=n_class_1),
    'target': [1] * n_class_1
})

In [ ]:
#concat means concatenate/combine.
#When you concatenate DataFrames, Pandas keeps their old indexes.
'''Notice that the index starts again from 0 for Class 1.

That's not what we want.

So:

.reset_index(drop=True)

creates a new continuous index:

What does drop=True mean?

It tells Pandas:

"Delete the old index instead of keeping it as a new column."

Without drop=True, Pandas would create an extra column called index.

Combine Class 0 and Class 1 into one DataFrame, then reset the row numbers from 0 to 999.'''


df=pd.concat([class_0,class_1]).reset_index(drop=True)

In [5]:
df.tail()

     feature_1  feature_2  target
995   1.376371   2.845701       1
996   2.239810   0.880077       1
997   1.131760   1.640703       1
998   2.902006   0.390305       1
999   2.697490   2.013570       1

In [6]:
df["target"].value_counts()

target
0    900
1    100
Name: count, dtype: int64

In [ ]:
# upsampling
#Select the majority AND MINORITY class
df_minority = df[df['target'] == 1]
df_majority = df[df['target'] == 0]

In [ ]:
#resample() is a function from Scikit-learn used to randomly sample rows from a dataset.
from sklearn.utils import resample

In [ ]:
'''This means sampling with replacement.
This is extremely important for upsampling.
Because we only have 100 minority samples but want 900 samples, 
we need to allow the same row to be selected multiple times.'''

df_minority_upsampled = resample(
    df_minority,
    replace=True,  # Sample with replacement
    n_samples=len(df_majority),
    random_state=42
)

df_minority_upsampled.shape

(900, 3)

In [10]:
df_minority_upsampled.head()

     feature_1  feature_2  target
951   1.125854   1.843917       1
992   2.196570   1.397425       1
914   1.932170   2.998053       1
971   2.272825   3.034197       1
960   2.870056   1.550485       1

In [11]:
df_upsampled=pd.concat([df_majority,df_minority_upsampled])

In [12]:
df_upsampled["target"].value_counts()

target
0    900
1    900
Name: count, dtype: int64

In [13]:
#Down sampling 
import pandas as pd 

np.random.seed(123)

#create a dataframe with the two classes
n_samples=1000
class_0_ratio=0.9
n_class_0=int(n_samples*class_0_ratio)
n_class_1=n_samples-n_class_0

class_0 = pd.DataFrame({
    'feature_1': np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature_2': np.random.normal(loc=0, scale=1, size=n_class_0),
    'target': [0] * n_class_0
})

class_1 = pd.DataFrame({
    'feature_1': np.random.normal(loc=2, scale=1, size=n_class_1),
    'feature_2': np.random.normal(loc=2, scale=1, size=n_class_1),
    'target': [1] * n_class_1
})


df=pd.concat([class_0,class_1]).reset_index(drop=True)
print(df["target"].value_counts())

target
0    900
1    100
Name: count, dtype: int64

In [14]:
#downsampling
df_minority = df[df['target'] == 1]
df_majority = df[df['target'] == 0]

In [16]:
from sklearn.utils import resample
df_majority_downsampled = resample(
    df_majority,
    replace=False,  # Sample with replacement
    n_samples=len(df_minority),
    random_state=42
)

df_majority_downsampled.shape

(100, 3)

In [17]:
df_downsampled=pd.concat([df_minority,df_majority_downsampled])

In [ ]:
'''value_counts → function ko refer kar rahe ho
value_counts() → function ko execute kar rahe ho'''

df_downsampled.target.value_counts()

target
1    100
0    100
Name: count, dtype: int64